/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    id: Principal;
    profileImage: string;
    name: string;
    phone: string;
}
export interface SupportTicket {
    id: bigint;
    subject: string;
    userId: Principal;
    message: string;
    timestamp: bigint;
}
export interface BookingItem {
    id: bigint;
    categoryId: bigint;
    bookingId: bigint;
    estimatedWeight: number;
    finalWeight?: number;
}
export interface Rating {
    id: bigint;
    bookingId: bigint;
    userId: Principal;
    partnerId: bigint;
    comment?: string;
    stars: bigint;
}
export interface Address {
    id: bigint;
    lat?: number;
    lng?: number;
    street: string;
    city: string;
    userId: Principal;
    addressLabel: string;
    pincode: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Partner {
    id: bigint;
    active: boolean;
    name: string;
    vehicle: string;
    rating: number;
    phone: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Payment {
    id: bigint;
    status: PaymentStatus;
    method: PaymentMethod;
    bookingId: bigint;
    amount: number;
    transactionId?: string;
}
export interface Notification {
    id: bigint;
    title: string;
    userId: Principal;
    icon: string;
    isRead: boolean;
    message: string;
    timestamp: bigint;
}
export interface ScrapRate {
    id: bigint;
    categoryId: bigint;
    pricePerKg: number;
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    totalFinalAmount?: number;
    scheduledTime: bigint;
    userId: Principal;
    partnerId?: bigint;
    addressId: bigint;
    totalEstimatedAmount: number;
}
export interface ScrapCategory {
    id: bigint;
    name: string;
    unit: string;
    parentId?: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ScrapRateWithCategory {
    id: bigint;
    categoryId: bigint;
    categoryName: string;
    pricePerKg: number;
}
export enum BookingStatus {
    on_the_way = "on_the_way",
    cancelled = "cancelled",
    pending = "pending",
    arrived = "arrived",
    completed = "completed",
    confirmed = "confirmed",
    partner_assigned = "partner_assigned"
}
export enum PaymentMethod {
    upi = "upi",
    cash = "cash"
}
export enum PaymentStatus {
    pending = "pending",
    completed = "completed",
    refunded = "refunded",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAddress(addressLabel: string, street: string, city: string, pincode: string, lat: number | null, lng: number | null): Promise<Address>;
    addBookingItem(bookingId: bigint, categoryId: bigint, estimatedWeight: number): Promise<BookingItem>;
    addPartner(name: string, phone: string, vehicle: string, rating: number, active: boolean): Promise<Partner>;
    addScrapCategory(name: string, parentId: bigint | null, unit: string): Promise<ScrapCategory>;
    addScrapRate(categoryId: bigint, pricePerKg: number): Promise<ScrapRate>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignPartnerToBooking(bookingId: bigint, partnerId: bigint): Promise<Booking>;
    autoAssignPartner(bookingId: bigint): Promise<Booking>;
    clearAllNotifications(): Promise<void>;
    createBooking(addressId: bigint, scheduledTime: bigint, totalEstimatedAmount: number): Promise<Booking>;
    createPayment(bookingId: bigint, amount: number, method: PaymentMethod, transactionId: string | null): Promise<Payment>;
    deleteAddress(id: bigint): Promise<void>;
    getAddressById(id: bigint): Promise<Address>;
    getAddresses(): Promise<Array<Address>>;
    getBookingById(id: bigint): Promise<Booking>;
    getBookingItems(bookingId: bigint): Promise<Array<BookingItem>>;
    getBookingPhase(status: BookingStatus): Promise<string>;
    getBookingsByAddressId(addressId: bigint): Promise<Array<Booking>>;
    getBookingsByPartnerId(partnerId: bigint): Promise<Array<Booking>>;
    getBookingsByStatus(status: BookingStatus): Promise<Array<Booking>>;
    getBookingsByUser(userId: Principal): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyBookings(): Promise<Array<Booking>>;
    getMySupportTickets(): Promise<Array<SupportTicket>>;
    getNotifications(): Promise<Array<Notification>>;
    getPartnerById(id: bigint): Promise<Partner>;
    getPartnerByPhone(phone: string): Promise<Partner | null>;
    getPartners(): Promise<Array<Partner>>;
    getPaymentByBookingId(bookingId: bigint): Promise<Payment | null>;
    getRatingByBookingId(bookingId: bigint): Promise<Rating | null>;
    getScrapCategories(): Promise<Array<ScrapCategory>>;
    getScrapCategoryById(id: bigint): Promise<ScrapCategory>;
    getScrapRateByCategoryId(categoryId: bigint): Promise<ScrapRate | null>;
    getScrapRates(): Promise<Array<ScrapRate>>;
    getScrapRatesWithCategories(): Promise<Array<ScrapRateWithCategory>>;
    getSupportTickets(): Promise<Array<SupportTicket>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markAllNotificationsRead(): Promise<void>;
    partnerAcceptBooking(bookingId: bigint, partnerId: bigint): Promise<Booking>;
    partnerUpdateBookingStatus(bookingId: bigint, partnerId: bigint): Promise<Booking>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitRating(bookingId: bigint, partnerId: bigint, stars: bigint, comment: string | null): Promise<Rating>;
    submitSupportTicket(subject: string, message: string): Promise<SupportTicket>;
    updateAddress(id: bigint, addressLabel: string, street: string, city: string, pincode: string, lat: number | null, lng: number | null): Promise<Address>;
    updateBookingItemFinalWeight(id: bigint, finalWeight: number): Promise<BookingItem>;
    updateBookingStatus(bookingId: bigint, newStatus: BookingStatus): Promise<Booking>;
    updatePartner(id: bigint, name: string, phone: string, vehicle: string, rating: number, active: boolean): Promise<Partner>;
    updatePaymentStatus(id: bigint, status: PaymentStatus): Promise<Payment>;
    updateScrapRate(categoryId: bigint, pricePerKg: number): Promise<ScrapRate>;
}
import type { Address as _Address, Booking as _Booking, BookingItem as _BookingItem, BookingStatus as _BookingStatus, Partner as _Partner, Payment as _Payment, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, Rating as _Rating, ScrapCategory as _ScrapCategory, ScrapRate as _ScrapRate, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAddress(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number | null, arg5: number | null): Promise<Address> {
        if (this.processError) {
            try {
                const result = await this.actor.addAddress(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Address_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAddress(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Address_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addBookingItem(arg0: bigint, arg1: bigint, arg2: number): Promise<BookingItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addBookingItem(arg0, arg1, arg2);
                return from_candid_BookingItem_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBookingItem(arg0, arg1, arg2);
            return from_candid_BookingItem_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPartner(arg0: string, arg1: string, arg2: string, arg3: number, arg4: boolean): Promise<Partner> {
        if (this.processError) {
            try {
                const result = await this.actor.addPartner(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPartner(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addScrapCategory(arg0: string, arg1: bigint | null, arg2: string): Promise<ScrapCategory> {
        if (this.processError) {
            try {
                const result = await this.actor.addScrapCategory(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_ScrapCategory_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScrapCategory(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_ScrapCategory_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async addScrapRate(arg0: bigint, arg1: number): Promise<ScrapRate> {
        if (this.processError) {
            try {
                const result = await this.actor.addScrapRate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScrapRate(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignPartnerToBooking(arg0: bigint, arg1: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.assignPartnerToBooking(arg0, arg1);
                return from_candid_Booking_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignPartnerToBooking(arg0, arg1);
            return from_candid_Booking_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async autoAssignPartner(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.autoAssignPartner(arg0);
                return from_candid_Booking_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.autoAssignPartner(arg0);
            return from_candid_Booking_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearAllNotifications(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllNotifications();
            return result;
        }
    }
    async createBooking(arg0: bigint, arg1: bigint, arg2: number): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2);
                return from_candid_Booking_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2);
            return from_candid_Booking_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPayment(arg0: bigint, arg1: number, arg2: PaymentMethod, arg3: string | null): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(arg0, arg1, to_candid_PaymentMethod_n23(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Payment_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(arg0, arg1, to_candid_PaymentMethod_n23(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Payment_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAddress(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAddress(arg0);
            return result;
        }
    }
    async getAddressById(arg0: bigint): Promise<Address> {
        if (this.processError) {
            try {
                const result = await this.actor.getAddressById(arg0);
                return from_candid_Address_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAddressById(arg0);
            return from_candid_Address_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAddresses(): Promise<Array<Address>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAddresses();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAddresses();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingById(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingById(arg0);
                return from_candid_Booking_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingById(arg0);
            return from_candid_Booking_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingItems(arg0: bigint): Promise<Array<BookingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingItems(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingItems(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingPhase(arg0: BookingStatus): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingPhase(to_candid_BookingStatus_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingPhase(to_candid_BookingStatus_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getBookingsByAddressId(arg0: bigint): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByAddressId(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByAddressId(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByPartnerId(arg0: bigint): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByPartnerId(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByPartnerId(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByStatus(arg0: BookingStatus): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByStatus(to_candid_BookingStatus_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByStatus(to_candid_BookingStatus_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByUser(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByUser(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByUser(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySupportTickets(): Promise<Array<SupportTicket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySupportTickets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySupportTickets();
            return result;
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return result;
        }
    }
    async getPartnerById(arg0: bigint): Promise<Partner> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerById(arg0);
            return result;
        }
    }
    async getPartnerByPhone(arg0: string): Promise<Partner | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerByPhone(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerByPhone(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartners(): Promise<Array<Partner>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartners();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartners();
            return result;
        }
    }
    async getPaymentByBookingId(arg0: bigint): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentByBookingId(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentByBookingId(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRatingByBookingId(arg0: bigint): Promise<Rating | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingByBookingId(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingByBookingId(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScrapCategories(): Promise<Array<ScrapCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScrapCategories();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScrapCategories();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScrapCategoryById(arg0: bigint): Promise<ScrapCategory> {
        if (this.processError) {
            try {
                const result = await this.actor.getScrapCategoryById(arg0);
                return from_candid_ScrapCategory_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScrapCategoryById(arg0);
            return from_candid_ScrapCategory_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScrapRateByCategoryId(arg0: bigint): Promise<ScrapRate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScrapRateByCategoryId(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScrapRateByCategoryId(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScrapRates(): Promise<Array<ScrapRate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScrapRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScrapRates();
            return result;
        }
    }
    async getScrapRatesWithCategories(): Promise<Array<ScrapRateWithCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScrapRatesWithCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScrapRatesWithCategories();
            return result;
        }
    }
    async getSupportTickets(): Promise<Array<SupportTicket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupportTickets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupportTickets();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async partnerAcceptBooking(arg0: bigint, arg1: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.partnerAcceptBooking(arg0, arg1);
                return from_candid_Booking_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.partnerAcceptBooking(arg0, arg1);
            return from_candid_Booking_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async partnerUpdateBookingStatus(arg0: bigint, arg1: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.partnerUpdateBookingStatus(arg0, arg1);
                return from_candid_Booking_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.partnerUpdateBookingStatus(arg0, arg1);
            return from_candid_Booking_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitRating(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string | null): Promise<Rating> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRating(arg0, arg1, arg2, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Rating_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRating(arg0, arg1, arg2, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Rating_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitSupportTicket(arg0: string, arg1: string): Promise<SupportTicket> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSupportTicket(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSupportTicket(arg0, arg1);
            return result;
        }
    }
    async updateAddress(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number | null, arg6: number | null): Promise<Address> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAddress(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6));
                return from_candid_Address_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAddress(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6));
            return from_candid_Address_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBookingItemFinalWeight(arg0: bigint, arg1: number): Promise<BookingItem> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingItemFinalWeight(arg0, arg1);
                return from_candid_BookingItem_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingItemFinalWeight(arg0, arg1);
            return from_candid_BookingItem_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n35(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Booking_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n35(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Booking_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePartner(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: number, arg5: boolean): Promise<Partner> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePartner(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePartner(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updatePaymentStatus(arg0: bigint, arg1: PaymentStatus): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n48(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Payment_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n48(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Payment_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateScrapRate(arg0: bigint, arg1: number): Promise<ScrapRate> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScrapRate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScrapRate(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Address_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Address): Address {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_BookingItem_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingItem): BookingItem {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Rating_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rating): Rating {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_ScrapCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScrapCategory): ScrapCategory {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Partner]): Partner | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : from_candid_Payment_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Rating]): Rating | null {
    return value.length === 0 ? null : from_candid_Rating_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ScrapRate]): ScrapRate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    lat: [] | [number];
    lng: [] | [number];
    street: string;
    city: string;
    userId: Principal;
    addressLabel: string;
    pincode: string;
}): {
    id: bigint;
    lat?: number;
    lng?: number;
    street: string;
    city: string;
    userId: Principal;
    addressLabel: string;
    pincode: string;
} {
    return {
        id: value.id,
        lat: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.lat)),
        lng: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.lng)),
        street: value.street,
        city: value.city,
        userId: value.userId,
        addressLabel: value.addressLabel,
        pincode: value.pincode
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    categoryId: bigint;
    bookingId: bigint;
    estimatedWeight: number;
    finalWeight: [] | [number];
}): {
    id: bigint;
    categoryId: bigint;
    bookingId: bigint;
    estimatedWeight: number;
    finalWeight?: number;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        bookingId: value.bookingId,
        estimatedWeight: value.estimatedWeight,
        finalWeight: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.finalWeight))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    unit: string;
    parentId: [] | [bigint];
}): {
    id: bigint;
    name: string;
    unit: string;
    parentId?: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        unit: value.unit,
        parentId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.parentId))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    totalFinalAmount: [] | [number];
    scheduledTime: bigint;
    userId: Principal;
    partnerId: [] | [bigint];
    addressId: bigint;
    totalEstimatedAmount: number;
}): {
    id: bigint;
    status: BookingStatus;
    totalFinalAmount?: number;
    scheduledTime: bigint;
    userId: Principal;
    partnerId?: bigint;
    addressId: bigint;
    totalEstimatedAmount: number;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n21(_uploadFile, _downloadFile, value.status),
        totalFinalAmount: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.totalFinalAmount)),
        scheduledTime: value.scheduledTime,
        userId: value.userId,
        partnerId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.partnerId)),
        addressId: value.addressId,
        totalEstimatedAmount: value.totalEstimatedAmount
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PaymentStatus;
    method: _PaymentMethod;
    bookingId: bigint;
    amount: number;
    transactionId: [] | [string];
}): {
    id: bigint;
    status: PaymentStatus;
    method: PaymentMethod;
    bookingId: bigint;
    amount: number;
    transactionId?: string;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n28(_uploadFile, _downloadFile, value.status),
        method: from_candid_PaymentMethod_n30(_uploadFile, _downloadFile, value.method),
        bookingId: value.bookingId,
        amount: value.amount,
        transactionId: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.transactionId))
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bookingId: bigint;
    userId: Principal;
    partnerId: bigint;
    comment: [] | [string];
    stars: bigint;
}): {
    id: bigint;
    bookingId: bigint;
    userId: Principal;
    partnerId: bigint;
    comment?: string;
    stars: bigint;
} {
    return {
        id: value.id,
        bookingId: value.bookingId,
        userId: value.userId,
        partnerId: value.partnerId,
        comment: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.comment)),
        stars: value.stars
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    on_the_way: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    arrived: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    partner_assigned: null;
}): BookingStatus {
    return "on_the_way" in value ? BookingStatus.on_the_way : "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "arrived" in value ? BookingStatus.arrived : "completed" in value ? BookingStatus.completed : "confirmed" in value ? BookingStatus.confirmed : "partner_assigned" in value ? BookingStatus.partner_assigned : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    refunded: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "completed" in value ? PaymentStatus.completed : "refunded" in value ? PaymentStatus.refunded : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    cash: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "cash" in value ? PaymentMethod.cash : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Address>): Array<Address> {
    return value.map((x)=>from_candid_Address_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingItem>): Array<BookingItem> {
    return value.map((x)=>from_candid_BookingItem_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScrapCategory>): Array<ScrapCategory> {
    return value.map((x)=>from_candid_ScrapCategory_n15(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    cash: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    on_the_way: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    arrived: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    partner_assigned: null;
} {
    return value == BookingStatus.on_the_way ? {
        on_the_way: null
    } : value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.arrived ? {
        arrived: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value == BookingStatus.partner_assigned ? {
        partner_assigned: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    completed: null;
} | {
    refunded: null;
} | {
    failed: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.completed ? {
        completed: null
    } : value == PaymentStatus.refunded ? {
        refunded: null
    } : value == PaymentStatus.failed ? {
        failed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
