/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Address = IDL.Record({
  'id' : IDL.Nat,
  'lat' : IDL.Opt(IDL.Float64),
  'lng' : IDL.Opt(IDL.Float64),
  'street' : IDL.Text,
  'city' : IDL.Text,
  'addressLabel' : IDL.Opt(IDL.Text),
  'pincode' : IDL.Text,
});
export const BookingItemRequest = IDL.Record({
  'categoryId' : IDL.Nat,
  'estimatedWeight' : IDL.Float64,
});
export const BookingRequest = IDL.Record({
  'scheduledTime' : IDL.Int,
  'address' : Address,
  'items' : IDL.Vec(BookingItemRequest),
  'totalEstimatedAmount' : IDL.Float64,
});
export const ServiceError = IDL.Variant({
  'invalidWeight' : IDL.Float64,
  'invalidAddress' : IDL.Null,
  'unauthorized' : IDL.Null,
  'missingItems' : IDL.Null,
  'backendError' : IDL.Text,
  'invalidCategory' : IDL.Nat,
});
export const BookingResponse = IDL.Record({
  'bookingId' : IDL.Nat,
  'partnerId' : IDL.Opt(IDL.Nat),
  'estimatedAmount' : IDL.Float64,
});
export const LanguageType = IDL.Variant({
  'en' : IDL.Null,
  'gu' : IDL.Null,
  'hi' : IDL.Null,
  'mr' : IDL.Null,
  'mw' : IDL.Null,
  'other' : IDL.Text,
});
export const ScrapShopStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ScrapShop = IDL.Record({
  'id' : IDL.Text,
  'preferredLanguage' : LanguageType,
  'ownerName' : IDL.Text,
  'area' : IDL.Text,
  'city' : IDL.Text,
  'scrapCategoriesHandled' : IDL.Vec(IDL.Nat),
  'email' : IDL.Text,
  'shopName' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
  'registrationStatus' : ScrapShopStatus,
  'registeredAt' : IDL.Int,
  'streetAddress' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'on_the_way' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'arrived' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'partner_assigned' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'profileImage' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'addresses' : IDL.Vec(Address),
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func(
      [BookingRequest],
      [IDL.Variant({ 'error' : ServiceError, 'success' : BookingResponse })],
      [],
    ),
  'createUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(Address)],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'alreadyExists' : IDL.Text,
          'invalidId' : IDL.Null,
        }),
      ],
      [],
    ),
  'getAllScrapShops' : IDL.Func([], [IDL.Vec(ScrapShop)], ['query']),
  'getBookingPhase' : IDL.Func([BookingStatus], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getScrapShopByPhone' : IDL.Func([IDL.Text], [IDL.Opt(ScrapShop)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerScrapShop' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Text,
      ],
      [ScrapShop],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateScrapShop' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat),
      ],
      [ScrapShop],
      [],
    ),
  'updateScrapShopStatus' : IDL.Func(
      [IDL.Text, ScrapShopStatus],
      [ScrapShop],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Address = IDL.Record({
    'id' : IDL.Nat,
    'lat' : IDL.Opt(IDL.Float64),
    'lng' : IDL.Opt(IDL.Float64),
    'street' : IDL.Text,
    'city' : IDL.Text,
    'addressLabel' : IDL.Opt(IDL.Text),
    'pincode' : IDL.Text,
  });
  const BookingItemRequest = IDL.Record({
    'categoryId' : IDL.Nat,
    'estimatedWeight' : IDL.Float64,
  });
  const BookingRequest = IDL.Record({
    'scheduledTime' : IDL.Int,
    'address' : Address,
    'items' : IDL.Vec(BookingItemRequest),
    'totalEstimatedAmount' : IDL.Float64,
  });
  const ServiceError = IDL.Variant({
    'invalidWeight' : IDL.Float64,
    'invalidAddress' : IDL.Null,
    'unauthorized' : IDL.Null,
    'missingItems' : IDL.Null,
    'backendError' : IDL.Text,
    'invalidCategory' : IDL.Nat,
  });
  const BookingResponse = IDL.Record({
    'bookingId' : IDL.Nat,
    'partnerId' : IDL.Opt(IDL.Nat),
    'estimatedAmount' : IDL.Float64,
  });
  const LanguageType = IDL.Variant({
    'en' : IDL.Null,
    'gu' : IDL.Null,
    'hi' : IDL.Null,
    'mr' : IDL.Null,
    'mw' : IDL.Null,
    'other' : IDL.Text,
  });
  const ScrapShopStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ScrapShop = IDL.Record({
    'id' : IDL.Text,
    'preferredLanguage' : LanguageType,
    'ownerName' : IDL.Text,
    'area' : IDL.Text,
    'city' : IDL.Text,
    'scrapCategoriesHandled' : IDL.Vec(IDL.Nat),
    'email' : IDL.Text,
    'shopName' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
    'registrationStatus' : ScrapShopStatus,
    'registeredAt' : IDL.Int,
    'streetAddress' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'on_the_way' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'arrived' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'partner_assigned' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'profileImage' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'addresses' : IDL.Vec(Address),
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [BookingRequest],
        [IDL.Variant({ 'error' : ServiceError, 'success' : BookingResponse })],
        [],
      ),
    'createUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(Address)],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'alreadyExists' : IDL.Text,
            'invalidId' : IDL.Null,
          }),
        ],
        [],
      ),
    'getAllScrapShops' : IDL.Func([], [IDL.Vec(ScrapShop)], ['query']),
    'getBookingPhase' : IDL.Func([BookingStatus], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getScrapShopByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ScrapShop)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerScrapShop' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Text,
        ],
        [ScrapShop],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateScrapShop' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat),
        ],
        [ScrapShop],
        [],
      ),
    'updateScrapShopStatus' : IDL.Func(
        [IDL.Text, ScrapShopStatus],
        [ScrapShop],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };