/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'id' : bigint,
  'lat' : [] | [number],
  'lng' : [] | [number],
  'street' : string,
  'city' : string,
  'userId' : Principal,
  'addressLabel' : string,
  'pincode' : string,
}
export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'totalFinalAmount' : [] | [number],
  'scheduledTime' : bigint,
  'userId' : Principal,
  'partnerId' : [] | [bigint],
  'addressId' : bigint,
  'totalEstimatedAmount' : number,
}
export interface BookingItem {
  'id' : bigint,
  'categoryId' : bigint,
  'bookingId' : bigint,
  'estimatedWeight' : number,
  'finalWeight' : [] | [number],
}
export type BookingStatus = { 'on_the_way' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'arrived' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'partner_assigned' : null };
export interface Notification {
  'id' : bigint,
  'title' : string,
  'userId' : Principal,
  'icon' : string,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
}
export interface Partner {
  'id' : bigint,
  'active' : boolean,
  'name' : string,
  'vehicle' : string,
  'rating' : number,
  'phone' : string,
}
export interface Payment {
  'id' : bigint,
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'bookingId' : bigint,
  'amount' : number,
  'transactionId' : [] | [string],
}
export type PaymentMethod = { 'upi' : null } |
  { 'cash' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export interface Rating {
  'id' : bigint,
  'bookingId' : bigint,
  'userId' : Principal,
  'partnerId' : bigint,
  'comment' : [] | [string],
  'stars' : bigint,
}
export interface ScrapCategory {
  'id' : bigint,
  'name' : string,
  'unit' : string,
  'parentId' : [] | [bigint],
}
export interface ScrapRate {
  'id' : bigint,
  'categoryId' : bigint,
  'pricePerKg' : number,
}
export interface ScrapRateWithCategory {
  'id' : bigint,
  'categoryId' : bigint,
  'categoryName' : string,
  'pricePerKg' : number,
}
export interface SupportTicket {
  'id' : bigint,
  'subject' : string,
  'userId' : Principal,
  'message' : string,
  'timestamp' : bigint,
}
export interface UserProfile {
  'id' : Principal,
  'profileImage' : string,
  'name' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAddress' : ActorMethod<
    [string, string, string, string, [] | [number], [] | [number]],
    Address
  >,
  'addBookingItem' : ActorMethod<[bigint, bigint, number], BookingItem>,
  'addPartner' : ActorMethod<
    [string, string, string, number, boolean],
    Partner
  >,
  'addScrapCategory' : ActorMethod<
    [string, [] | [bigint], string],
    ScrapCategory
  >,
  'addScrapRate' : ActorMethod<[bigint, number], ScrapRate>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignPartnerToBooking' : ActorMethod<[bigint, bigint], Booking>,
  'autoAssignPartner' : ActorMethod<[bigint], Booking>,
  'clearAllNotifications' : ActorMethod<[], undefined>,
  'createBooking' : ActorMethod<[bigint, bigint, number], Booking>,
  'createPayment' : ActorMethod<
    [bigint, number, PaymentMethod, [] | [string]],
    Payment
  >,
  'deleteAddress' : ActorMethod<[bigint], undefined>,
  'getAddressById' : ActorMethod<[bigint], Address>,
  'getAddresses' : ActorMethod<[], Array<Address>>,
  'getBookingById' : ActorMethod<[bigint], Booking>,
  'getBookingItems' : ActorMethod<[bigint], Array<BookingItem>>,
  'getBookingPhase' : ActorMethod<[BookingStatus], string>,
  'getBookingsByAddressId' : ActorMethod<[bigint], Array<Booking>>,
  'getBookingsByPartnerId' : ActorMethod<[bigint], Array<Booking>>,
  'getBookingsByStatus' : ActorMethod<[BookingStatus], Array<Booking>>,
  'getBookingsByUser' : ActorMethod<[Principal], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getMySupportTickets' : ActorMethod<[], Array<SupportTicket>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPartnerById' : ActorMethod<[bigint], Partner>,
  'getPartnerByPhone' : ActorMethod<[string], [] | [Partner]>,
  'getPartners' : ActorMethod<[], Array<Partner>>,
  'getPaymentByBookingId' : ActorMethod<[bigint], [] | [Payment]>,
  'getRatingByBookingId' : ActorMethod<[bigint], [] | [Rating]>,
  'getScrapCategories' : ActorMethod<[], Array<ScrapCategory>>,
  'getScrapCategoryById' : ActorMethod<[bigint], ScrapCategory>,
  'getScrapRateByCategoryId' : ActorMethod<[bigint], [] | [ScrapRate]>,
  'getScrapRates' : ActorMethod<[], Array<ScrapRate>>,
  'getScrapRatesWithCategories' : ActorMethod<[], Array<ScrapRateWithCategory>>,
  'getSupportTickets' : ActorMethod<[], Array<SupportTicket>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'partnerAcceptBooking' : ActorMethod<[bigint, bigint], Booking>,
  'partnerUpdateBookingStatus' : ActorMethod<[bigint, bigint], Booking>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRating' : ActorMethod<[bigint, bigint, bigint, [] | [string]], Rating>,
  'submitSupportTicket' : ActorMethod<[string, string], SupportTicket>,
  'updateAddress' : ActorMethod<
    [bigint, string, string, string, string, [] | [number], [] | [number]],
    Address
  >,
  'updateBookingItemFinalWeight' : ActorMethod<[bigint, number], BookingItem>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], Booking>,
  'updatePartner' : ActorMethod<
    [bigint, string, string, string, number, boolean],
    Partner
  >,
  'updatePaymentStatus' : ActorMethod<[bigint, PaymentStatus], Payment>,
  'updateScrapRate' : ActorMethod<[bigint, number], ScrapRate>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];