/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Address = IDL.Record({
  'id' : IDL.Nat,
  'lat' : IDL.Opt(IDL.Float64),
  'lng' : IDL.Opt(IDL.Float64),
  'street' : IDL.Text,
  'city' : IDL.Text,
  'userId' : IDL.Principal,
  'addressLabel' : IDL.Text,
  'pincode' : IDL.Text,
});
export const BookingItem = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'bookingId' : IDL.Nat,
  'estimatedWeight' : IDL.Float64,
  'finalWeight' : IDL.Opt(IDL.Float64),
});
export const Partner = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'vehicle' : IDL.Text,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
});
export const ScrapCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'parentId' : IDL.Opt(IDL.Nat),
});
export const ScrapRate = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'pricePerKg' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'on_the_way' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'arrived' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'partner_assigned' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'totalFinalAmount' : IDL.Opt(IDL.Float64),
  'scheduledTime' : IDL.Int,
  'userId' : IDL.Principal,
  'partnerId' : IDL.Opt(IDL.Nat),
  'addressId' : IDL.Nat,
  'totalEstimatedAmount' : IDL.Float64,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'cash' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'bookingId' : IDL.Nat,
  'amount' : IDL.Float64,
  'transactionId' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'profileImage' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const SupportTicket = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'userId' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'icon' : IDL.Text,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Rating = IDL.Record({
  'id' : IDL.Nat,
  'bookingId' : IDL.Nat,
  'userId' : IDL.Principal,
  'partnerId' : IDL.Nat,
  'comment' : IDL.Opt(IDL.Text),
  'stars' : IDL.Nat,
});
export const ScrapRateWithCategory = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'categoryName' : IDL.Text,
  'pricePerKg' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAddress' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
      ],
      [Address],
      [],
    ),
  'addBookingItem' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Float64],
      [BookingItem],
      [],
    ),
  'addPartner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
      [Partner],
      [],
    ),
  'addScrapCategory' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
      [ScrapCategory],
      [],
    ),
  'addScrapRate' : IDL.Func([IDL.Nat, IDL.Float64], [ScrapRate], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPartnerToBooking' : IDL.Func([IDL.Nat, IDL.Nat], [Booking], []),
  'autoAssignPartner' : IDL.Func([IDL.Nat], [Booking], []),
  'clearAllNotifications' : IDL.Func([], [], []),
  'createBooking' : IDL.Func([IDL.Nat, IDL.Int, IDL.Float64], [Booking], []),
  'createPayment' : IDL.Func(
      [IDL.Nat, IDL.Float64, PaymentMethod, IDL.Opt(IDL.Text)],
      [Payment],
      [],
    ),
  'deleteAddress' : IDL.Func([IDL.Nat], [], []),
  'getAddressById' : IDL.Func([IDL.Nat], [Address], ['query']),
  'getAddresses' : IDL.Func([], [IDL.Vec(Address)], ['query']),
  'getBookingById' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getBookingItems' : IDL.Func([IDL.Nat], [IDL.Vec(BookingItem)], ['query']),
  'getBookingPhase' : IDL.Func([BookingStatus], [IDL.Text], ['query']),
  'getBookingsByAddressId' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getBookingsByPartnerId' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getBookingsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMySupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPartnerById' : IDL.Func([IDL.Nat], [Partner], ['query']),
  'getPartnerByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Partner)], ['query']),
  'getPartners' : IDL.Func([], [IDL.Vec(Partner)], ['query']),
  'getPaymentByBookingId' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
  'getRatingByBookingId' : IDL.Func([IDL.Nat], [IDL.Opt(Rating)], ['query']),
  'getScrapCategories' : IDL.Func([], [IDL.Vec(ScrapCategory)], ['query']),
  'getScrapCategoryById' : IDL.Func([IDL.Nat], [ScrapCategory], ['query']),
  'getScrapRateByCategoryId' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ScrapRate)],
      ['query'],
    ),
  'getScrapRates' : IDL.Func([], [IDL.Vec(ScrapRate)], ['query']),
  'getScrapRatesWithCategories' : IDL.Func(
      [],
      [IDL.Vec(ScrapRateWithCategory)],
      ['query'],
    ),
  'getSupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'partnerAcceptBooking' : IDL.Func([IDL.Nat, IDL.Nat], [Booking], []),
  'partnerUpdateBookingStatus' : IDL.Func([IDL.Nat, IDL.Nat], [Booking], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRating' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
      [Rating],
      [],
    ),
  'submitSupportTicket' : IDL.Func([IDL.Text, IDL.Text], [SupportTicket], []),
  'updateAddress' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
      ],
      [Address],
      [],
    ),
  'updateBookingItemFinalWeight' : IDL.Func(
      [IDL.Nat, IDL.Float64],
      [BookingItem],
      [],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [Booking], []),
  'updatePartner' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
      [Partner],
      [],
    ),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [Payment], []),
  'updateScrapRate' : IDL.Func([IDL.Nat, IDL.Float64], [ScrapRate], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Address = IDL.Record({
    'id' : IDL.Nat,
    'lat' : IDL.Opt(IDL.Float64),
    'lng' : IDL.Opt(IDL.Float64),
    'street' : IDL.Text,
    'city' : IDL.Text,
    'userId' : IDL.Principal,
    'addressLabel' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const BookingItem = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'bookingId' : IDL.Nat,
    'estimatedWeight' : IDL.Float64,
    'finalWeight' : IDL.Opt(IDL.Float64),
  });
  const Partner = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'vehicle' : IDL.Text,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const ScrapCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'parentId' : IDL.Opt(IDL.Nat),
  });
  const ScrapRate = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'pricePerKg' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'on_the_way' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'arrived' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'partner_assigned' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'totalFinalAmount' : IDL.Opt(IDL.Float64),
    'scheduledTime' : IDL.Int,
    'userId' : IDL.Principal,
    'partnerId' : IDL.Opt(IDL.Nat),
    'addressId' : IDL.Nat,
    'totalEstimatedAmount' : IDL.Float64,
  });
  const PaymentMethod = IDL.Variant({ 'upi' : IDL.Null, 'cash' : IDL.Null });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'method' : PaymentMethod,
    'bookingId' : IDL.Nat,
    'amount' : IDL.Float64,
    'transactionId' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'profileImage' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SupportTicket = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'userId' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'icon' : IDL.Text,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Rating = IDL.Record({
    'id' : IDL.Nat,
    'bookingId' : IDL.Nat,
    'userId' : IDL.Principal,
    'partnerId' : IDL.Nat,
    'comment' : IDL.Opt(IDL.Text),
    'stars' : IDL.Nat,
  });
  const ScrapRateWithCategory = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'categoryName' : IDL.Text,
    'pricePerKg' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAddress' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
        ],
        [Address],
        [],
      ),
    'addBookingItem' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Float64],
        [BookingItem],
        [],
      ),
    'addPartner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
        [Partner],
        [],
      ),
    'addScrapCategory' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
        [ScrapCategory],
        [],
      ),
    'addScrapRate' : IDL.Func([IDL.Nat, IDL.Float64], [ScrapRate], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPartnerToBooking' : IDL.Func([IDL.Nat, IDL.Nat], [Booking], []),
    'autoAssignPartner' : IDL.Func([IDL.Nat], [Booking], []),
    'clearAllNotifications' : IDL.Func([], [], []),
    'createBooking' : IDL.Func([IDL.Nat, IDL.Int, IDL.Float64], [Booking], []),
    'createPayment' : IDL.Func(
        [IDL.Nat, IDL.Float64, PaymentMethod, IDL.Opt(IDL.Text)],
        [Payment],
        [],
      ),
    'deleteAddress' : IDL.Func([IDL.Nat], [], []),
    'getAddressById' : IDL.Func([IDL.Nat], [Address], ['query']),
    'getAddresses' : IDL.Func([], [IDL.Vec(Address)], ['query']),
    'getBookingById' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getBookingItems' : IDL.Func([IDL.Nat], [IDL.Vec(BookingItem)], ['query']),
    'getBookingPhase' : IDL.Func([BookingStatus], [IDL.Text], ['query']),
    'getBookingsByAddressId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByPartnerId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMySupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPartnerById' : IDL.Func([IDL.Nat], [Partner], ['query']),
    'getPartnerByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Partner)], ['query']),
    'getPartners' : IDL.Func([], [IDL.Vec(Partner)], ['query']),
    'getPaymentByBookingId' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Payment)],
        ['query'],
      ),
    'getRatingByBookingId' : IDL.Func([IDL.Nat], [IDL.Opt(Rating)], ['query']),
    'getScrapCategories' : IDL.Func([], [IDL.Vec(ScrapCategory)], ['query']),
    'getScrapCategoryById' : IDL.Func([IDL.Nat], [ScrapCategory], ['query']),
    'getScrapRateByCategoryId' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ScrapRate)],
        ['query'],
      ),
    'getScrapRates' : IDL.Func([], [IDL.Vec(ScrapRate)], ['query']),
    'getScrapRatesWithCategories' : IDL.Func(
        [],
        [IDL.Vec(ScrapRateWithCategory)],
        ['query'],
      ),
    'getSupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'partnerAcceptBooking' : IDL.Func([IDL.Nat, IDL.Nat], [Booking], []),
    'partnerUpdateBookingStatus' : IDL.Func([IDL.Nat, IDL.Nat], [Booking], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRating' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
        [Rating],
        [],
      ),
    'submitSupportTicket' : IDL.Func([IDL.Text, IDL.Text], [SupportTicket], []),
    'updateAddress' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
        ],
        [Address],
        [],
      ),
    'updateBookingItemFinalWeight' : IDL.Func(
        [IDL.Nat, IDL.Float64],
        [BookingItem],
        [],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [Booking], []),
    'updatePartner' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
        [Partner],
        [],
      ),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [Payment], []),
    'updateScrapRate' : IDL.Func([IDL.Nat, IDL.Float64], [ScrapRate], []),
  });
};

export const init = ({ IDL }) => { return []; };