/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'id' : bigint,
  'lat' : [] | [number],
  'lng' : [] | [number],
  'street' : string,
  'city' : string,
  'addressLabel' : [] | [string],
  'pincode' : string,
}
export interface BookingItemRequest {
  'categoryId' : bigint,
  'estimatedWeight' : number,
}
export interface BookingRequest {
  'scheduledTime' : bigint,
  'address' : Address,
  'items' : Array<BookingItemRequest>,
  'totalEstimatedAmount' : number,
}
export interface BookingResponse {
  'bookingId' : bigint,
  'partnerId' : [] | [bigint],
  'estimatedAmount' : number,
}
export type BookingStatus = { 'on_the_way' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'arrived' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'partner_assigned' : null };
export type LanguageType = { 'en' : null } |
  { 'gu' : null } |
  { 'hi' : null } |
  { 'mr' : null } |
  { 'mw' : null } |
  { 'other' : string };
export interface ScrapShop {
  'id' : string,
  'preferredLanguage' : LanguageType,
  'ownerName' : string,
  'area' : string,
  'city' : string,
  'scrapCategoriesHandled' : Array<bigint>,
  'email' : string,
  'shopName' : string,
  'phone' : string,
  'pincode' : string,
  'registrationStatus' : ScrapShopStatus,
  'registeredAt' : bigint,
  'streetAddress' : string,
}
export type ScrapShopStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ServiceError = { 'invalidWeight' : number } |
  { 'invalidAddress' : null } |
  { 'unauthorized' : null } |
  { 'missingItems' : null } |
  { 'backendError' : string } |
  { 'invalidCategory' : bigint };
export interface UserProfile {
  'profileImage' : [] | [string],
  'name' : string,
  'email' : [] | [string],
  'addresses' : Array<Address>,
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<
    [BookingRequest],
    { 'error' : ServiceError } |
      { 'success' : BookingResponse }
  >,
  'createUserProfile' : ActorMethod<
    [string, string, [] | [Address]],
    { 'ok' : null } |
      { 'alreadyExists' : string } |
      { 'invalidId' : null }
  >,
  'getAllScrapShops' : ActorMethod<[], Array<ScrapShop>>,
  'getBookingPhase' : ActorMethod<[BookingStatus], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getScrapShopByPhone' : ActorMethod<[string], [] | [ScrapShop]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileById' : ActorMethod<[string], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerScrapShop' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<bigint>,
      string,
    ],
    ScrapShop
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateScrapShop' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<bigint>,
    ],
    ScrapShop
  >,
  'updateScrapShopStatus' : ActorMethod<[string, ScrapShopStatus], ScrapShop>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];